import { modelLabel } from "./labels.mjs";
import path from "node:path";
import fs from "node:fs";
import { PLUGIN_ROOT, CCO_AGENT_NAMES, LEGACY_AGENT_NAMES, readTextSafe, writeTextIfChanged, workspacePaths, readJsonSafe, writeJson, windowAgentName, nowIso } from "./common.mjs";

/**
 * Cursor honors a subagent's `model:` line for project subagents (<workspace>/.cursor/agents) and user
 * subagents (~/.cursor/agents); plugin-provided agents always inherit the chat model. Project scope writes
 * the agents into the workspace; user scope writes them once into ~/.cursor/agents (nothing in any repo).
 */
export const GENERATED_MARKER_PREFIX = "<!-- generated by cursor-ai-cost-optimizer";
export const ALIAS_MARKER_PREFIX = "<!-- cco-alias-for:";
export const GENERATED_MARKER = "<!-- generated by cursor-ai-cost-optimizer (CCO). Edit .cursor/cco.json and re-run cco-init instead of editing this file. -->";

/** <ws>/.cursor/agents in project scope; ~/.cursor/agents in user scope (both honor `model:` in the IDE). */
export function workspaceAgentsDir(workspace) {
  return workspacePaths(workspace).agentsDir;
}

export function pluginAgentPath(name) {
  return path.join(PLUGIN_ROOT, "agents", `${name}.md`);
}

export function renderWorkspaceAgent(role, modelId, name = role) {
  // Templates (by role) may be checked out with CRLF on Windows (git autocrlf); normalize before parsing the frontmatter.
  const source = (readTextSafe(pluginAgentPath(role)) || "").replace(/\r\n/g, "\n");
  if (!source) {
    return null;
  }
  const model = modelId && modelId !== "inherit" ? modelId : "inherit";
  const withModel = source.replace(/^model:\s*.*$/m, `model: ${model}`).replace(/^name:\s*.*$/m, `name: ${name}`).replace(/\{\{MODEL_LABEL\}\}/g, model === "inherit" ? "the chat model" : modelLabel(model));
  const closing = withModel.indexOf("\n---\n", 4);
  if (closing < 0) {
    return null;
  }
  return `${withModel.slice(0, closing + 5)}${GENERATED_MARKER}\n${withModel.slice(closing + 5)}`;
}

/** Role → suffix Cursor shows on the card after the model name ("Composer 2.5 Fast"). */
const ROLE_SUFFIX = { "fast-tier": "fast", "balanced-tier": "balanced", "deep-tier": "deep", "fast-research": "research", "tier-verifier": "verifier" };

/** "claude-sonnet-5-thinking-high" → "claude-sonnet-5"; "cursor-grok-4.6-high" → "grok-4.6"; "composer-2.5" stays. */
export function modelSlug(modelId) {
  let id = String(modelId || "").toLowerCase().replace(/^cursor-/, "");
  id = id.replace(/-(thinking|fast|low|medium|high|xhigh|max|1m|nozdr|zdr|extra|no)(?=-|$)/g, "");
  id = id.replace(/-+$/, "").replace(/[^a-z0-9.-]+/g, "-");
  return id || "model";
}

/** The subagent name Cursor displays: the model it runs on, then the tier. Falls back to the role name. */
export function agentNameFor(role, modelId) {
  const suffix = ROLE_SUFFIX[role];
  if (!suffix || !modelId || modelId === "inherit") {
    return role;
  }
  return `${modelSlug(modelId)}-${suffix}`;
}

/** Which role a subagent name plays, or null when it is not ours (accepts role names and pre-0.3 cco-* names). */
export function roleOf(name) {
  const n = String(name || "").toLowerCase();
  if (CCO_AGENT_NAMES.includes(n)) return n;
  const legacy = { "cco-fast": "fast-tier", "cco-balanced": "balanced-tier", "cco-deep": "deep-tier", "cco-explore": "fast-research", "cco-verifier": "tier-verifier" };
  if (legacy[n]) return legacy[n];
  const m = n.match(/-(fast|balanced|deep|research|verifier)$/);
  if (!m) return null;
  return { fast: "fast-tier", balanced: "balanced-tier", deep: "deep-tier", research: "fast-research", verifier: "tier-verifier" }[m[1]];
}

function namesPath(workspace) {
  const paths = workspacePaths(workspace);
  return path.join(paths.scope === "user" ? paths.root : paths.ccoDir, "agent-names.json");
}

/** Role → current subagent name for this workspace (falls back to the role names). */
export function agentNames(workspace) {
  const stored = workspace ? readJsonSafe(namesPath(workspace)) : null;
  const out = {};
  for (const role of CCO_AGENT_NAMES) {
    out[role] = typeof stored?.[role] === "string" && stored[role] ? stored[role] : role;
  }
  return out;
}

/**
 * Write the tier subagents, named after the model each one runs on. Generated files under any other name
 * (a previous mapping, the pre-0.3 cco-* names) are removed; user-authored files are never touched.
 */
export function writeWorkspaceAgents(workspace, tierModels) {
  const dir = workspaceAgentsDir(workspace);
  const results = [];
  const names = {};
  for (const role of CCO_AGENT_NAMES) {
    const modelId = tierModels[role] || "inherit";
    const name = agentNameFor(role, modelId);
    names[role] = name;
    const target = path.join(dir, `${name}.md`);
    const existing = readTextSafe(target);
    if (existing && !existing.includes(GENERATED_MARKER_PREFIX)) {
      results.push({ name, role, path: target, action: "skipped_user_file", model: null });
      continue;
    }
    const content = renderWorkspaceAgent(role, modelId, name);
    if (!content) {
      results.push({ name, role, path: target, action: "template_missing", model: null });
      continue;
    }
    const written = writeTextIfChanged(target, content);
    results.push({ name, role, path: target, action: written ? "written" : "unchanged", model: modelId });
  }
  // Generated files under other names (a previous mapping, the pre-0.3 cco-* names) stay as aliases of the tier
  // they played, on the new model: Cursor's Task tool keeps listing the names it saw when the window opened, and a
  // remote window never refreshes that list until it is reloaded. Aliases are removed at the next window start.
  const keep = new Set(Object.values(names).map((n) => `${n}.md`));
  const aliases = {};
  try {
    for (const file of fs.readdirSync(dir)) {
      if (!file.endsWith(".md") || keep.has(file)) continue;
      const text = readTextSafe(path.join(dir, file));
      if (!text || !text.includes(GENERATED_MARKER_PREFIX)) continue;
      const oldName = file.slice(0, -3);
      const role = roleOf(oldName);
      const target = role ? names[role] : null;
      if (target) {
        // Kept as it was (same model): a window that still lists this name also still runs the definition it
        // loaded with it, so the cards and estimates stay honest until the window is reloaded.
        if (!text.includes(ALIAS_MARKER_PREFIX)) {
          writeTextIfChanged(path.join(dir, file), text.includes(GENERATED_MARKER) ? text.replace(GENERATED_MARKER, `${GENERATED_MARKER}\n${ALIAS_MARKER_PREFIX} ${target} -->`) : `${text.trimEnd()}\n${ALIAS_MARKER_PREFIX} ${target} -->\n`);
        }
        aliases[oldName] = target;
      } else {
        try { fs.unlinkSync(path.join(dir, file)); } catch {}
      }
    }
  } catch {}
  try { writeJson(namesPath(workspace), Object.keys(aliases).length ? { ...names, _aliases: aliases } : names); } catch {}
  // user scope: the agents-only local plugin for the Cursor CLI mirrors what was just written
  try {
    const paths = workspacePaths(workspace);
    if (paths.scope === "user") {
      const mirror = path.join(path.dirname(paths.agentsDir), "plugins", "local", "cco-agents");
      if (fs.existsSync(path.join(mirror, ".cursor-plugin", "plugin.json"))) {
        for (const file of fs.readdirSync(path.join(mirror, "agents"))) fs.unlinkSync(path.join(mirror, "agents", file));
        for (const file of fs.readdirSync(dir)) {
          if (file.endsWith(".md") && (readTextSafe(path.join(dir, file)) || "").includes(GENERATED_MARKER_PREFIX)) fs.copyFileSync(path.join(dir, file), path.join(mirror, "agents", file));
        }
      }
    }
  } catch {}
  return results;
}

/** Alias files (old names kept for a window that still lists them); removed when a window opens. */
export function removeAliasAgents(workspace) {
  const dir = workspaceAgentsDir(workspace);
  const removed = [];
  try {
    for (const file of fs.readdirSync(dir)) {
      if (!file.endsWith(".md")) continue;
      const text = readTextSafe(path.join(dir, file));
      if (text && text.includes(ALIAS_MARKER_PREFIX)) {
        try { fs.unlinkSync(path.join(dir, file)); removed.push(file.slice(0, -3)); } catch {}
      }
    }
  } catch {}
  if (removed.length) {
    try {
      const stored = readJsonSafe(namesPath(workspace)) || {};
      if (stored._aliases) { delete stored._aliases; writeJson(namesPath(workspace), stored); }
    } catch {}
  }
  return removed;
}

/** Names of every generated subagent file present (current names and aliases). */
export function listGeneratedAgents(workspace) {
  const dir = workspaceAgentsDir(workspace);
  const out = [];
  try {
    for (const file of fs.readdirSync(dir)) {
      if (!file.endsWith(".md")) continue;
      const text = readTextSafe(path.join(dir, file));
      if (text && text.includes(GENERATED_MARKER_PREFIX)) out.push(file.slice(0, -3));
    }
  } catch {}
  return out.sort();
}

function windowAgentsPath(workspace) {
  const paths = workspacePaths(workspace);
  return path.join(paths.stateDir, "window-agents.json");
}

/** What the Task tool of the current window accepts: recorded at workspaceOpen or learned from its own error. */
export function recordWindowAgents(workspace, names, source) {
  const list = [...new Set((names || []).map((n) => String(n)))].sort();
  const noneOfOurs = !list.some((n) => roleOf(n));
  const record = { ts: nowIso(), source, names: list, noneOfOurs };
  try { fs.mkdirSync(path.dirname(windowAgentsPath(workspace)), { recursive: true }); writeJson(windowAgentsPath(workspace), record); } catch {}
  return record;
}

export function readWindowAgents(workspace) {
  return readJsonSafe(windowAgentsPath(workspace));
}

/** Role → the name to hand the model in this window (an alias when the window predates a rename). */
export function agentNamesForWindow(workspace) {
  const current = agentNames(workspace);
  const dir = path.dirname(windowAgentsPath(workspace));
  const out = {};
  for (const role of CCO_AGENT_NAMES) {
    out[role] = windowAgentName(dir, role, current[role]);
  }
  return out;
}

export function readWorkspaceAgentModel(workspace, roleOrName) {
  const names = agentNames(workspace);
  const name = names[roleOrName] || roleOrName;
  const text = readTextSafe(path.join(workspaceAgentsDir(workspace), `${name}.md`));
  if (!text) {
    return null;
  }
  const match = text.match(/^model:\s*(.+)$/m);
  return match ? match[1].trim() : null;
}

/** A workspace is set up for CCO when its tier agents exist. */
export function workspaceHasAgents(workspace) {
  return Boolean(readTextSafe(path.join(workspaceAgentsDir(workspace), `${agentNames(workspace)["fast-tier"]}.md`)));
}

/** Generated agents under the pre-0.3 names (cco-*.md) are replaced by the user-facing names; user-authored files are kept. */
export function removeLegacyAgents(dir) {
  const removed = [];
  for (const name of LEGACY_AGENT_NAMES) {
    const file = path.join(dir, `${name}.md`);
    const text = readTextSafe(file);
    if (text && text.includes(GENERATED_MARKER_PREFIX)) {
      try {
        fs.unlinkSync(file);
        removed.push(name);
      } catch {}
    }
  }
  return removed;
}
