import path from "node:path";
import { PLUGIN_ROOT, CCO_AGENT_NAMES, readTextSafe, writeTextIfChanged } from "./common.mjs";

/**
 * Cursor honors a subagent's `model:` line only for project subagents (<workspace>/.cursor/agents).
 * Plugin-provided agents always inherit the chat model, and the CLI does not load ~/.cursor/agents.
 * So enabling CCO for a workspace writes four small agent files there; nothing else goes into repos.
 */
export const GENERATED_MARKER_PREFIX = "<!-- generated by cursor-ai-cost-optimizer";
export const GENERATED_MARKER = "<!-- generated by cursor-ai-cost-optimizer (CCO). Edit .cursor/cco.json and re-run cco-init instead of editing this file. -->";

export function workspaceAgentsDir(workspace) {
  return path.join(workspace, ".cursor", "agents");
}

export function pluginAgentPath(name) {
  return path.join(PLUGIN_ROOT, "agents", `${name}.md`);
}

export function renderWorkspaceAgent(name, modelId) {
  const source = readTextSafe(pluginAgentPath(name));
  if (!source) {
    return null;
  }
  const model = modelId && modelId !== "inherit" ? modelId : "inherit";
  const withModel = source.replace(/^model:\s*.*$/m, `model: ${model}`);
  const closing = withModel.indexOf("\n---\n", 4);
  if (closing < 0) {
    return null;
  }
  return `${withModel.slice(0, closing + 5)}${GENERATED_MARKER}\n${withModel.slice(closing + 5)}`;
}

/** Write <workspace>/.cursor/agents/cco-*.md. Never overwrites a file that is not ours. */
export function writeWorkspaceAgents(workspace, tierModels) {
  const dir = workspaceAgentsDir(workspace);
  const results = [];
  for (const name of CCO_AGENT_NAMES) {
    const modelId = tierModels[name] || "inherit";
    const target = path.join(dir, `${name}.md`);
    const existing = readTextSafe(target);
    if (existing && !existing.includes(GENERATED_MARKER_PREFIX)) { // any CCO-generated version (older markers included) is ours to refresh
      results.push({ name, path: target, action: "skipped_user_file", model: null });
      continue;
    }
    const content = renderWorkspaceAgent(name, modelId);
    if (!content) {
      results.push({ name, path: target, action: "template_missing", model: null });
      continue;
    }
    const written = writeTextIfChanged(target, content);
    results.push({ name, path: target, action: written ? "written" : "unchanged", model: modelId });
  }
  return results;
}

export function readWorkspaceAgentModel(workspace, name) {
  const text = readTextSafe(path.join(workspaceAgentsDir(workspace), `${name}.md`));
  if (!text) {
    return null;
  }
  const match = text.match(/^model:\s*(.+)$/m);
  return match ? match[1].trim() : null;
}

/** A workspace is set up for CCO when its tier agents exist. */
export function workspaceHasAgents(workspace) {
  return Boolean(readTextSafe(path.join(workspaceAgentsDir(workspace), "cco-fast.md")));
}
