import path from "node:path";
import fs from "node:fs";
import { PLUGIN_ROOT, CCO_AGENT_NAMES, LEGACY_AGENT_NAMES, readTextSafe, writeTextIfChanged, workspacePaths } from "./common.mjs";

/**
 * Cursor honors a subagent's `model:` line for project subagents (<workspace>/.cursor/agents) and user
 * subagents (~/.cursor/agents); plugin-provided agents always inherit the chat model. Project scope writes
 * the agents into the workspace; user scope writes them once into ~/.cursor/agents (nothing in any repo).
 */
export const GENERATED_MARKER_PREFIX = "<!-- generated by cursor-ai-cost-optimizer";
export const GENERATED_MARKER = "<!-- generated by cursor-ai-cost-optimizer (CCO). Edit .cursor/cco.json and re-run cco-init instead of editing this file. -->";

/** <ws>/.cursor/agents in project scope; ~/.cursor/agents in user scope (both honor `model:` in the IDE). */
export function workspaceAgentsDir(workspace) {
  return workspacePaths(workspace).agentsDir;
}

export function pluginAgentPath(name) {
  return path.join(PLUGIN_ROOT, "agents", `${name}.md`);
}

export function renderWorkspaceAgent(name, modelId) {
  // Templates may be checked out with CRLF on Windows (git autocrlf); normalize before parsing the frontmatter.
  const source = (readTextSafe(pluginAgentPath(name)) || "").replace(/\r\n/g, "\n");
  if (!source) {
    return null;
  }
  const model = modelId && modelId !== "inherit" ? modelId : "inherit";
  const withModel = source.replace(/^model:\s*.*$/m, `model: ${model}`);
  const closing = withModel.indexOf("\n---\n", 4);
  if (closing < 0) {
    return null;
  }
  return `${withModel.slice(0, closing + 5)}${GENERATED_MARKER}\n${withModel.slice(closing + 5)}`;
}

/** Write <workspace>/.cursor/agents/cco-*.md. Never overwrites a file that is not ours. */
export function writeWorkspaceAgents(workspace, tierModels) {
  const dir = workspaceAgentsDir(workspace);
  const results = [];
  removeLegacyAgents(dir);
  for (const name of CCO_AGENT_NAMES) {
    const modelId = tierModels[name] || "inherit";
    const target = path.join(dir, `${name}.md`);
    const existing = readTextSafe(target);
    if (existing && !existing.includes(GENERATED_MARKER_PREFIX)) { // any CCO-generated version (older markers included) is ours to refresh
      results.push({ name, path: target, action: "skipped_user_file", model: null });
      continue;
    }
    const content = renderWorkspaceAgent(name, modelId);
    if (!content) {
      results.push({ name, path: target, action: "template_missing", model: null });
      continue;
    }
    const written = writeTextIfChanged(target, content);
    results.push({ name, path: target, action: written ? "written" : "unchanged", model: modelId });
  }
  return results;
}

export function readWorkspaceAgentModel(workspace, name) {
  const text = readTextSafe(path.join(workspaceAgentsDir(workspace), `${name}.md`));
  if (!text) {
    return null;
  }
  const match = text.match(/^model:\s*(.+)$/m);
  return match ? match[1].trim() : null;
}

/** A workspace is set up for CCO when its tier agents exist. */
export function workspaceHasAgents(workspace) {
  return Boolean(readTextSafe(path.join(workspaceAgentsDir(workspace), "fast-tier.md")));
}

/** Generated agents under the pre-0.3 names (cco-*.md) are replaced by the user-facing names; user-authored files are kept. */
export function removeLegacyAgents(dir) {
  const removed = [];
  for (const name of LEGACY_AGENT_NAMES) {
    const file = path.join(dir, `${name}.md`);
    const text = readTextSafe(file);
    if (text && text.includes(GENERATED_MARKER_PREFIX)) {
      try {
        fs.unlinkSync(file);
        removed.push(name);
      } catch {}
    }
  }
  return removed;
}
