/**
 * Install / uninstall / doctor logic for the AI Cost Optimizer extension.
 * Deliberately free of `vscode` imports so it can be unit-tested with node:test.
 *
 * Everything is PROJECT-LOCAL under <workspace>/.cursor/ (Cursor's own convention); nothing is written to
 * the home directory. The plugin's own `cco-init.mjs --workspace <ws> --no-probe` produces the layout the
 * marketplace plugin would (run with CCO_PLUGIN_ROOT = the extension's bundled plugin copy):
 *   .cursor/hooks.json          merge-preserving entries `node .cursor/cco-hook.mjs <event>` (the shim is committed next to it)
 *   .cursor/agents/cco-*.md     four tier subagents with real models (generated marker; user files never overwritten)
 *   .cursor/cco.json            settings, optional ("enabled": false opts the project out); created only when a setting is changed
 *   .cursor/cco-hook.mjs        shim (a no-op for teammates without the plugin)
 *   .cursor/cco/                plugin-path.txt (-> bundled plugin), runtime.json, pricing.json, state/ (git-ignored)
 * The extension then adds, for IDE users without the marketplace plugin and for machines without Node:
 *   .cursor/rules/cco-routing.mdc, .cursor/skills/cco-* /SKILL.md, .cursor/commands/cco*.md   (from the plugin)
 *   .cursor/cco/bin/cco-hook[.exe]   self-contained hook binary; hook commands become `"<abs binary>" <event>`
 *   .cursor/cco/extension-manifest.json   what the extension added (for uninstall/doctor)
 */
import * as crypto from "crypto";
import * as fs from "fs";
import * as os from "os";
import * as path from "path";
import { spawn, spawnSync } from "child_process";

export const BINARY_NAME = "cco-hook";
export const CCO_HOOK_COMMAND_RE = /cco-hook|\.cursor[\\/]cco[\\/]scripts[\\/]cco-/;
export const GENERATED_AGENT_MARKER = "generated by cursor-ai-cost-optimizer";
export const CCO_AGENT_NAMES = ["cco-fast", "cco-balanced", "cco-deep", "cco-verifier"];
export const MANIFEST_NAME = "extension-manifest.json";
export type HookMode = "binary" | "node";
export type HookRuntimePreference = "auto" | "binary" | "node";

export interface HookEntry {
  command: string;
  matcher?: string;
  timeout?: number;
  [key: string]: unknown;
}
export interface HooksFile {
  version?: number;
  hooks?: Record<string, HookEntry[]>;
  [key: string]: unknown;
}

export interface Options {
  /** extension's bundled plugin copy (resources/plugin) = CCO_PLUGIN_ROOT */
  pluginRoot: string;
  binaryPath?: string | null;
  extensionVersion?: string;
  hookRuntime?: HookRuntimePreference;
  nodePath?: string | null;
  timeoutMs?: number;
  probe?: boolean;
}

export interface Manifest {
  version: number;
  extensionVersion?: string;
  installedAt: string;
  hookMode: HookMode;
  pluginRoot: string;
  binary: string | null;
  files: string[];
}

export interface RunResult {
  ran: boolean;
  runtime: "node" | "binary" | "none";
  command: string | null;
  status: number | null;
  stdout: string;
  error: string | null;
}

export interface InstallResult {
  workspace: string;
  hookMode: HookMode;
  binaryPath: string | null;
  hooksPath: string;
  hookEvents: string[];
  files: string[];
  agents: Record<string, string | null>;
  init: RunResult;
  manifestPath: string;
  legacyRemoved: string[];
}

export interface UninstallResult {
  removed: string[];
  init: RunResult;
  hooksFileFound: boolean;
}

export interface DoctorResult {
  installed: boolean;
  changed: boolean;
  hookMode: HookMode | null;
  actions: string[];
}

export interface WorkspaceStatus {
  installed: boolean;
  enabled: boolean;
  reason: string | null;
  hookMode: HookMode | null;
  agents: Record<string, string | null>;
}

// ---------------------------------------------------------------------------------------------
// helpers
// ---------------------------------------------------------------------------------------------

function ensureDir(p: string): void {
  fs.mkdirSync(p, { recursive: true });
}
function readJsonOr<T>(filePath: string, fallback: T): T {
  try {
    return JSON.parse(fs.readFileSync(filePath, "utf8")) as T;
  } catch {
    return fallback;
  }
}
function writeJson(filePath: string, value: unknown): void {
  ensureDir(path.dirname(filePath));
  fs.writeFileSync(filePath, `${JSON.stringify(value, null, 2)}\n`, "utf8");
}
function readTextOr(filePath: string, fallback: string | null = null): string | null {
  try {
    return fs.readFileSync(filePath, "utf8");
  } catch {
    return fallback;
  }
}
export function listFiles(dir: string, prefix = ""): string[] {
  if (!fs.existsSync(dir)) {
    return [];
  }
  const out: string[] = [];
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const rel = prefix ? `${prefix}/${entry.name}` : entry.name;
    if (entry.isDirectory()) {
      out.push(...listFiles(path.join(dir, entry.name), rel));
    } else if (entry.isFile()) {
      out.push(rel);
    }
  }
  return out.sort();
}
function sha256File(filePath: string): string {
  return crypto.createHash("sha256").update(fs.readFileSync(filePath)).digest("hex");
}
function sameFile(a: string, b: string): boolean {
  try {
    const sa = fs.statSync(a);
    const sb = fs.statSync(b);
    if (sa.size !== sb.size) {
      return false;
    }
  } catch {
    return false;
  }
  try {
    return fs.statSync(a).size === fs.statSync(b).size && sha256File(a) === sha256File(b);
  } catch {
    return false;
  }
}
function rmdirIfEmpty(dir: string): void {
  try {
    if (fs.existsSync(dir) && fs.readdirSync(dir).length === 0) {
      fs.rmdirSync(dir);
    }
  } catch {}
}
function toPosix(p: string): string {
  return p.split(path.sep).join("/");
}

export function workspacePaths(workspace: string) {
  const cursorDir = path.join(workspace, ".cursor");
  const ccoDir = path.join(cursorDir, "cco");
  return {
    cursorDir,
    ccoDir,
    hooksPath: path.join(cursorDir, "hooks.json"),
    configPath: path.join(cursorDir, "cco.json"),
    agentsDir: path.join(cursorDir, "agents"),
    rulesDir: path.join(cursorDir, "rules"),
    skillsDir: path.join(cursorDir, "skills"),
    commandsDir: path.join(cursorDir, "commands"),
    shimPath: path.join(cursorDir, "cco-hook.mjs"),
    pluginPathFile: path.join(ccoDir, "plugin-path.txt"),
    binDir: path.join(ccoDir, "bin"),
    binaryPath: path.join(ccoDir, "bin", binaryFileName()),
    manifestPath: path.join(ccoDir, MANIFEST_NAME),
    stateDir: path.join(ccoDir, "state"),
  };
}

// ---------------------------------------------------------------------------------------------
// platform binary / node runtime
// ---------------------------------------------------------------------------------------------

export function hostTarget(): string {
  const plat = os.platform();
  const arch = os.arch() === "arm64" ? "arm64" : "x64";
  return `${plat === "win32" ? "win32" : plat === "darwin" ? "darwin" : "linux"}-${arch}`;
}
export function binaryFileName(target: string = hostTarget()): string {
  return target.startsWith("win32") ? `${BINARY_NAME}.exe` : BINARY_NAME;
}
/** Newest of bin/cco-hook (platform VSIX), bin/<target>/, dist-bin/<target>/ (development checkout). */
export function findBundledBinary(extensionRoot: string, target: string = hostTarget()): string | null {
  const name = binaryFileName(target);
  let best: { file: string; mtime: number } | null = null;
  for (const candidate of [path.join(extensionRoot, "bin", name), path.join(extensionRoot, "bin", target, name), path.join(extensionRoot, "dist-bin", target, name)]) {
    try {
      const st = fs.statSync(candidate);
      if (st.isFile() && (!best || st.mtimeMs > best.mtime)) {
        best = { file: candidate, mtime: st.mtimeMs };
      }
    } catch {}
  }
  return best ? best.file : null;
}

export interface NodeRuntime {
  command: string;
  env: Record<string, string>;
  label: string;
}
/** cco.nodePath / CCO_NODE, then `node` on PATH, then the current executable run as node (Cursor's own node). */
const nodeCache = new Map<string, NodeRuntime | null>();
export function findNode(nodePath?: string | null): NodeRuntime | null {
  const key = `${nodePath ?? ""}|${process.env.CCO_NODE ?? ""}`;
  if (nodeCache.has(key)) {
    return nodeCache.get(key) as NodeRuntime | null;
  }
  const found = findNodeUncached(nodePath);
  nodeCache.set(key, found);
  return found;
}
function findNodeUncached(nodePath?: string | null): NodeRuntime | null {
  const candidates: NodeRuntime[] = [];
  for (const explicit of [nodePath, process.env.CCO_NODE]) {
    if (explicit) {
      candidates.push({ command: explicit, env: {}, label: explicit });
    }
  }
  candidates.push({ command: "node", env: {}, label: "node (PATH)" });
  candidates.push({ command: process.execPath, env: { ELECTRON_RUN_AS_NODE: "1" }, label: `${process.execPath} (ELECTRON_RUN_AS_NODE)` });
  for (const c of candidates) {
    try {
      const probe = spawnSync(c.command, ["-e", "process.stdout.write(String(process.versions.node))"], { encoding: "utf8", timeout: 10_000, env: { ...process.env, ...c.env } });
      if (probe.status === 0 && Number(String(probe.stdout || "").split(".")[0]) >= 18) {
        return c;
      }
    } catch {}
  }
  return null;
}
function copyBinary(src: string, dst: string): void {
  ensureDir(path.dirname(dst));
  fs.copyFileSync(src, dst);
  if (process.platform !== "win32") {
    fs.chmodSync(dst, 0o755);
  }
}

/**
 * Run one of the plugin's setup scripts for a workspace: `node <pluginRoot>/scripts/<script> <args>` when a
 * Node >= 18 is available (and hookRuntime is not "binary"), else the bundled binary's equivalent command
 * (`cco-hook init ...`), which needs no Node.
 */
function resolvePluginRunner(script: "cco-init.mjs" | "cco-discover-models.mjs", args: string[], opts: Options, extraEnv: Record<string, string>): { command: string; argv: string[]; env: Record<string, string>; runtime: RunResult["runtime"]; error?: string } {
  const env: Record<string, string> = { ...(process.env as Record<string, string>), CCO_PLUGIN_ROOT: opts.pluginRoot };
  delete env.CCO_SCOPE;
  delete env.CCO_STATE_ROOT;
  Object.assign(env, extraEnv);
  // hookRuntime "binary" means "this machine may have no Node": run the setup through the binary as well.
  const hasBinary = Boolean(opts.binaryPath && fs.existsSync(opts.binaryPath));
  const node = opts.hookRuntime === "binary" && hasBinary ? null : findNode(opts.nodePath);
  if (node) {
    Object.assign(env, node.env);
    return { command: node.command, argv: [path.join(opts.pluginRoot, "scripts", script), ...args], env, runtime: "node" };
  }
  if (opts.binaryPath && fs.existsSync(opts.binaryPath)) {
    return { command: opts.binaryPath, argv: [script === "cco-init.mjs" ? "init" : "discover", ...args], env, runtime: "binary" };
  }
  return { command: "", argv: [], env, runtime: "none", error: "Neither Node.js >= 18 nor a bundled cco-hook binary is available to run the plugin's setup script." };
}

export function runPluginScript(workspace: string, script: "cco-init.mjs" | "cco-discover-models.mjs", args: string[], opts: Options, extraEnv: Record<string, string> = {}): RunResult {
  const r = resolvePluginRunner(script, args, opts, extraEnv);
  if (r.runtime === "none") {
    return { ran: false, runtime: "none", command: null, status: null, stdout: "", error: r.error ?? null };
  }
  const res = spawnSync(r.command, r.argv, { cwd: workspace, encoding: "utf8", env: r.env, timeout: opts.timeoutMs ?? 180_000, input: "" });
  return {
    ran: true,
    runtime: r.runtime,
    command: `${r.command} ${r.argv.join(" ")}`,
    status: res.status,
    stdout: String(res.stdout || "").slice(-4000),
    error: res.status === 0 ? null : String(res.error?.message || res.stderr || `exit ${res.status}`).slice(0, 800),
  };
}

/** Same as runPluginScript, without blocking the extension host (Copilot rule: never block activation or the UI thread). */
export function runPluginScriptAsync(workspace: string, script: "cco-init.mjs" | "cco-discover-models.mjs", args: string[], opts: Options, extraEnv: Record<string, string> = {}, signal?: AbortSignal): Promise<RunResult> {
  const r = resolvePluginRunner(script, args, opts, extraEnv);
  if (r.runtime === "none") {
    return Promise.resolve({ ran: false, runtime: "none", command: null, status: null, stdout: "", error: r.error ?? null });
  }
  return new Promise((resolve) => {
    let stdout = "";
    let stderr = "";
    let done = false;
    const child = spawn(r.command, r.argv, { cwd: workspace, env: r.env, stdio: ["ignore", "pipe", "pipe"] });
    const timer = setTimeout(() => {
      if (!done) {
        child.kill();
      }
    }, opts.timeoutMs ?? 180_000);
    if (signal) {
      const onAbort = () => child.kill();
      if (signal.aborted) {
        onAbort();
      } else {
        signal.addEventListener("abort", onAbort, { once: true });
      }
    }
    child.stdout?.on("data", (d) => (stdout += String(d)));
    child.stderr?.on("data", (d) => (stderr += String(d)));
    const finish = (status: number | null, err?: Error) => {
      if (done) {
        return;
      }
      done = true;
      clearTimeout(timer);
      resolve({ ran: true, runtime: r.runtime, command: `${r.command} ${r.argv.join(" ")}`, status, stdout: stdout.slice(-4000), error: status === 0 ? null : signal?.aborted ? "cancelled" : String(err?.message || stderr || `exit ${status}`).slice(0, 800) });
    };
    child.on("error", (err) => finish(null, err));
    child.on("close", (code) => finish(code));
  });
}

// ---------------------------------------------------------------------------------------------
// hooks.json
// ---------------------------------------------------------------------------------------------

export function isCcoHookCommand(command: unknown): boolean {
  return typeof command === "string" && CCO_HOOK_COMMAND_RE.test(command);
}
export function quoteCommandPath(p: string): string {
  return `"${p.replace(/"/g, '\\"')}"`;
}
export function hookCommandFor(event: string, mode: HookMode, binaryPath?: string | null): string {
  return mode === "binary" && binaryPath ? `${quoteCommandPath(binaryPath)} ${event}` : `node .cursor/cco-hook.mjs ${event}`;
}
/** Account for the plugin's hooks/hooks.json entries (keeps matcher/timeout). */
export function buildHookEntries(pluginHooks: HooksFile, mode: HookMode, binaryPath?: string | null): Record<string, HookEntry[]> {
  const out: Record<string, HookEntry[]> = {};
  for (const [event, entries] of Object.entries(pluginHooks?.hooks || {})) {
    if (!Array.isArray(entries)) {
      continue;
    }
    out[event] = entries
      .filter((e) => e && typeof e.command === "string")
      .map((e) => {
        const entry: HookEntry = { ...e, command: hookCommandFor(event, mode, binaryPath) };
        if (entry.matcher === undefined) {
          delete entry.matcher;
        }
        if (entry.timeout === undefined) {
          delete entry.timeout;
        }
        return entry;
      });
  }
  return out;
}
/** Keep foreign entries, drop previous CCO entries (any event), append ours. */
export function mergeHooks(existing: HooksFile | null | undefined, ours: Record<string, HookEntry[]>): HooksFile {
  const base: HooksFile = existing && typeof existing === "object" ? { ...existing } : {};
  base.version = typeof base.version === "number" ? base.version : 1;
  const merged: Record<string, HookEntry[]> = {};
  for (const [event, entries] of Object.entries(base.hooks && typeof base.hooks === "object" ? base.hooks : {})) {
    const kept = (Array.isArray(entries) ? entries : []).filter((e) => !isCcoHookCommand(e?.command));
    if (kept.length) {
      merged[event] = kept;
    }
  }
  for (const [event, entries] of Object.entries(ours)) {
    if (entries.length) {
      merged[event] = [...(merged[event] || []), ...entries];
    }
  }
  base.hooks = merged;
  return base;
}
export function stripCcoHooks(existing: HooksFile | null | undefined): HooksFile | null {
  if (!existing || typeof existing !== "object") {
    return null;
  }
  const out = mergeHooks(existing, {});
  const otherKeys = Object.keys(out).filter((k) => k !== "version" && k !== "hooks");
  return Object.keys(out.hooks || {}).length === 0 && otherKeys.length === 0 ? null : out;
}
export function ccoHookEntries(file: HooksFile | null | undefined): Record<string, HookEntry[]> {
  const out: Record<string, HookEntry[]> = {};
  for (const [event, entries] of Object.entries(file?.hooks || {})) {
    const ours = (Array.isArray(entries) ? entries : []).filter((e) => isCcoHookCommand(e?.command));
    if (ours.length) {
      out[event] = ours;
    }
  }
  return out;
}
function sameEntries(a: Record<string, HookEntry[]>, b: Record<string, HookEntry[]>): boolean {
  const norm = (x: Record<string, HookEntry[]>) => JSON.stringify(Object.keys(x).sort().map((k) => [k, x[k].map((e) => JSON.stringify(e)).sort()]));
  return norm(a) === norm(b);
}
/** Rewrite our entries in <ws>/.cursor/hooks.json to the given form; returns the events written. */
function writeHookEntries(workspace: string, opts: Options, mode: HookMode, binaryPath: string | null): string[] {
  const p = workspacePaths(workspace);
  const pluginHooks = readJsonOr<HooksFile>(path.join(opts.pluginRoot, "hooks", "hooks.json"), { version: 1, hooks: {} });
  const ours = buildHookEntries(pluginHooks, mode, binaryPath);
  writeJson(p.hooksPath, mergeHooks(readJsonOr<HooksFile | null>(p.hooksPath, null), ours));
  return Object.keys(ours);
}

// ---------------------------------------------------------------------------------------------
// plan / status
// ---------------------------------------------------------------------------------------------

export function readWorkspaceAgents(workspace: string): Record<string, string | null> {
  const out: Record<string, string | null> = {};
  for (const name of CCO_AGENT_NAMES) {
    const text = readTextOr(path.join(workspace, ".cursor", "agents", `${name}.md`));
    const m = text ? text.match(/^model:\s*(.+)$/m) : null;
    out[name] = m ? m[1].trim() : null;
  }
  return out;
}

/** Extension-added files, relative to the workspace (rule, skills, commands from the bundled plugin). */
/** Only what routing needs in the workspace: the rule. Skills and chat commands stay in the extension. */
export function extensionAssetList(pluginRoot: string): string[] {
  const out: string[] = [];
  for (const rel of listFiles(path.join(pluginRoot, "rules"))) {
    out.push(`.cursor/rules/${rel}`);
  }
  return out.sort();
}

/** What an install will create/modify under <ws>/.cursor (shown before the first write). */
export function plannedFiles(workspace: string, opts: Options): { creates: string[]; modifies: string[]; hookMode: HookMode } {
  const p = workspacePaths(workspace);
  const hookMode = decideHookMode(opts);
  const creates = [".cursor/cco-hook.mjs", ".cursor/agents/cco-{fast,balanced,deep,verifier,explore}.md", ...extensionAssetList(opts.pluginRoot), ".cursor/cco/ (runtime, prices, logs; ignores itself in git)"];
  if (hookMode === "binary") {
    creates.push(`.cursor/cco/bin/${binaryFileName()}`);
  }
  creates.push(`.cursor/cco/${MANIFEST_NAME}`);
  const modifies = [fs.existsSync(p.hooksPath) ? ".cursor/hooks.json (CCO entries merged; other entries kept)" : ".cursor/hooks.json"];
  return { creates, modifies, hookMode };
}

export function decideHookMode(opts: Options): HookMode {
  const pref = opts.hookRuntime || "auto";
  const hasBinary = Boolean(opts.binaryPath && fs.existsSync(opts.binaryPath));
  if (pref === "binary") {
    if (!hasBinary) {
      throw new Error(`cco.hookRuntime is "binary" but this extension build has no hook binary for ${hostTarget()}.`);
    }
    return "binary";
  }
  if (pref === "node") {
    return "node";
  }
  // auto: Node keeps .cursor/hooks.json portable (the shim is committed next to it); the binary is the
  // fallback for machines without Node >= 18 and makes hooks.json reference a machine-local path.
  return findNode(opts.nodePath) ? "node" : hasBinary ? "binary" : "node";
}

export function workspaceStatus(workspace: string): WorkspaceStatus {
  const p = workspacePaths(workspace);
  const manifest = readJsonOr<Manifest | null>(p.manifestPath, null);
  const agents = readWorkspaceAgents(workspace);
  const cfg = readJsonOr<{ enabled?: boolean } | null>(p.configPath, null);
  const hasAgents = fs.existsSync(path.join(p.agentsDir, "cco-fast.md"));
  const hooksInstalled = Object.keys(ccoHookEntries(readJsonOr<HooksFile | null>(p.hooksPath, null))).length > 0;
  let reason: string | null = null;
  if (cfg && cfg.enabled === false) {
    reason = "workspace_opt_out";
  } else if (!hasAgents) {
    reason = "workspace_not_set_up";
  } else if (!hooksInstalled) {
    reason = "hooks_missing";
  }
  return { installed: Boolean(manifest) || (hasAgents && hooksInstalled), enabled: reason === null, reason, hookMode: manifest?.hookMode ?? (hooksInstalled ? "node" : null), agents };
}

// ---------------------------------------------------------------------------------------------
// install
// ---------------------------------------------------------------------------------------------

/** Files earlier (pre-release) extension versions put under .cursor/cco that the plugin layout does not use. */
export function cleanupLegacyWorkspace(workspace: string): string[] {
  const p = workspacePaths(workspace);
  const removed: string[] = [];
  for (const stale of ["scripts", "config", "agents", "install-manifest.json"]) {
    const target = path.join(p.ccoDir, stale);
    if (fs.existsSync(target)) {
      fs.rmSync(target, { recursive: true, force: true });
      removed.push(toPosix(path.relative(workspace, target)));
    }
  }
  for (const stale of ["cco-runtime.json", "cco-pricing.json"]) {
    const target = path.join(p.cursorDir, stale);
    if (fs.existsSync(target)) {
      fs.rmSync(target, { force: true });
      removed.push(toPosix(path.relative(workspace, target)));
    }
  }
  return removed;
}

function writeExtensionAssets(workspace: string, pluginRoot: string): string[] {
  const written: string[] = [];
  const copy = (srcDir: string, dstDir: string, prefix: string) => {
    for (const rel of listFiles(srcDir)) {
      const to = path.join(dstDir, ...rel.split("/"));
      ensureDir(path.dirname(to));
      fs.copyFileSync(path.join(srcDir, ...rel.split("/")), to);
      written.push(`${prefix}/${rel}`);
    }
  };
  const p = workspacePaths(workspace);
  copy(path.join(pluginRoot, "rules"), p.rulesDir, ".cursor/rules");
  return written.sort();
}

/**
 * Set up a workspace: the plugin's cco-init (identical files to the marketplace plugin), then the extension's
 * additions (rule/skills/commands; binary + binary-form hook commands when in binary mode) and a manifest.
 */
export async function installWorkspace(workspace: string, opts: Options, signal?: AbortSignal): Promise<InstallResult> {
  const p = workspacePaths(workspace);
  const hookMode = decideHookMode(opts);
  const legacyRemoved = cleanupLegacyWorkspace(workspace);

  const init = await runPluginScriptAsync(workspace, "cco-init.mjs", ["--workspace", workspace, opts.probe ? "--probe" : "--no-probe"], opts, {}, signal);
  if (!init.ran) {
    throw new Error(init.error || "setup could not run");
  }
  if (init.status !== 0) {
    throw new Error(`cco-init failed (${init.runtime}): ${init.error}\n${init.stdout}`);
  }
  // cco-init pins the plugin the shim should use; make sure it is our bundled copy.
  fs.writeFileSync(p.pluginPathFile, `${opts.pluginRoot}\n`, "utf8");

  let binaryPath: string | null = null;
  fs.rmSync(p.binDir, { recursive: true, force: true });
  if (hookMode === "binary") {
    copyBinary(opts.binaryPath as string, p.binaryPath);
    binaryPath = p.binaryPath;
  }
  const hookEvents = writeHookEntries(workspace, opts, hookMode, binaryPath);

  const previous = readJsonOr<Manifest | null>(p.manifestPath, null);
  const files = writeExtensionAssets(workspace, opts.pluginRoot);
  for (const stale of (previous?.files || []).filter((f) => !files.includes(f) && !f.startsWith(".cursor/cco/"))) {
    fs.rmSync(path.join(workspace, ...stale.split("/")), { force: true });
  }
  if (binaryPath) {
    files.push(toPosix(path.relative(workspace, binaryPath)));
  }
  const manifest: Manifest = { version: 4, extensionVersion: opts.extensionVersion, installedAt: new Date().toISOString(), hookMode, pluginRoot: opts.pluginRoot, binary: binaryPath, files: files.sort() };
  writeJson(p.manifestPath, manifest);
  return { workspace, hookMode, binaryPath, hooksPath: p.hooksPath, hookEvents, files: manifest.files, agents: readWorkspaceAgents(workspace), init, manifestPath: p.manifestPath, legacyRemoved };
}

// ---------------------------------------------------------------------------------------------
// doctor
// ---------------------------------------------------------------------------------------------

/**
 * Repair an installed workspace without touching user files: repoint plugin-path.txt and hook entries when
 * the extension path/binary path went stale (extension update, moved workspace), refresh the binary bytes,
 * and refresh the rule/skills/commands when the extension version changed. No-op where CCO was not installed.
 */
export function doctorWorkspace(workspace: string, opts: Options): DoctorResult {
  const p = workspacePaths(workspace);
  const manifest = readJsonOr<Manifest | null>(p.manifestPath, null);
  if (!manifest) {
    return { installed: false, changed: false, hookMode: null, actions: [] };
  }
  const actions: string[] = [];
  if ((readTextOr(p.pluginPathFile) || "").trim() !== opts.pluginRoot) {
    fs.writeFileSync(p.pluginPathFile, `${opts.pluginRoot}\n`, "utf8");
    actions.push("plugin_path_repointed");
  }
  let useBinary = fs.existsSync(p.binaryPath);
  const pref = opts.hookRuntime || "auto";
  if (pref !== "node" && opts.binaryPath && fs.existsSync(opts.binaryPath)) {
    if (!useBinary) {
      copyBinary(opts.binaryPath, p.binaryPath);
      actions.push("binary_installed");
      useBinary = true;
    } else if (!sameFile(opts.binaryPath, p.binaryPath)) {
      try {
        copyBinary(opts.binaryPath, p.binaryPath);
        actions.push("binary_refreshed");
      } catch (error) {
        actions.push(`binary_refresh_failed:${String((error as Error)?.message ?? error)}`);
      }
    }
  }
  if (pref === "node" && useBinary) {
    fs.rmSync(p.binDir, { recursive: true, force: true });
    actions.push("binary_removed");
    useBinary = false;
  }
  const hookMode: HookMode = useBinary ? "binary" : "node";
  const pluginHooks = readJsonOr<HooksFile>(path.join(opts.pluginRoot, "hooks", "hooks.json"), { version: 1, hooks: {} });
  const ours = buildHookEntries(pluginHooks, hookMode, useBinary ? p.binaryPath : null);
  const existing = readJsonOr<HooksFile | null>(p.hooksPath, null);
  if (!existing) {
    writeJson(p.hooksPath, mergeHooks(null, ours));
    actions.push("hooks_recreated");
  } else if (!sameEntries(ccoHookEntries(existing), ours)) {
    writeJson(p.hooksPath, mergeHooks(existing, ours));
    actions.push("hooks_repointed");
  }
  if (opts.extensionVersion && manifest.extensionVersion !== opts.extensionVersion) {
    writeExtensionAssets(workspace, opts.pluginRoot);
    actions.push("assets_refreshed");
  }
  if (actions.length) {
    manifest.hookMode = hookMode;
    manifest.binary = useBinary ? p.binaryPath : null;
    manifest.pluginRoot = opts.pluginRoot;
    manifest.extensionVersion = opts.extensionVersion ?? manifest.extensionVersion;
    manifest.files = Array.from(new Set([...manifest.files.filter((f) => !f.startsWith(".cursor/cco/bin/")), ...(useBinary ? [toPosix(path.relative(workspace, p.binaryPath))] : [])])).sort();
    writeJson(p.manifestPath, manifest);
  }
  return { installed: true, changed: actions.length > 0, hookMode, actions };
}

// ---------------------------------------------------------------------------------------------
// uninstall
// ---------------------------------------------------------------------------------------------

/**
 * `cco-init --workspace <ws> --uninstall` (removes hook entries, generated agents, .cursor/cco.json and
 * .cursor/cco/ — foreign hook entries are preserved) plus the rule/skills/commands the extension added.
 * Falls back to an in-process removal when no runtime is available.
 */
export async function uninstallWorkspace(workspace: string, opts: Options): Promise<UninstallResult> {
  const p = workspacePaths(workspace);
  const manifest = readJsonOr<Manifest | null>(p.manifestPath, null);
  const removed: string[] = [];
  const hooksFileFound = fs.existsSync(p.hooksPath);
  const binaryForRun = fs.existsSync(p.binaryPath) ? p.binaryPath : opts.binaryPath;
  const init = await runPluginScriptAsync(workspace, "cco-init.mjs", ["--workspace", workspace, "--uninstall"], { ...opts, binaryPath: binaryForRun });
  if (!init.ran || init.status !== 0) {
    // in-process fallback: same effect as cco-init --uninstall
    const existing = readJsonOr<HooksFile | null>(p.hooksPath, null);
    if (existing) {
      const stripped = stripCcoHooks(existing);
      if (stripped) {
        writeJson(p.hooksPath, stripped);
      } else {
        fs.rmSync(p.hooksPath, { force: true });
      }
    }
    for (const name of CCO_AGENT_NAMES) {
      const file = path.join(p.agentsDir, `${name}.md`);
      if ((readTextOr(file) || "").includes(GENERATED_AGENT_MARKER)) {
        fs.rmSync(file, { force: true });
        removed.push(toPosix(path.relative(workspace, file)));
      }
    }
    fs.rmSync(p.configPath, { force: true });
  }
  if (fs.existsSync(p.ccoDir)) {
    fs.rmSync(p.ccoDir, { recursive: true, force: true });
  }
  removed.push(".cursor/cco/", ".cursor/cco-hook.mjs", ".cursor/cco.json", ".cursor/agents/cco-*.md (generated)");
  const files = manifest?.files || extensionAssetList(opts.pluginRoot);
  for (const rel of files) {
    if (rel.startsWith(".cursor/cco/")) {
      continue;
    }
    const abs = path.join(workspace, ...rel.split("/"));
    if (fs.existsSync(abs)) {
      fs.rmSync(abs, { force: true });
      removed.push(rel);
    }
  }
  for (const d of [p.skillsDir]) {
    if (fs.existsSync(d)) {
      for (const entry of fs.readdirSync(d)) {
        rmdirIfEmpty(path.join(d, entry));
      }
    }
  }
  for (const d of [p.rulesDir, p.skillsDir, p.commandsDir, p.agentsDir]) {
    rmdirIfEmpty(d);
  }
  rmdirIfEmpty(p.cursorDir);
  return { removed, init, hooksFileFound };
}
