/**
 * User scope ("Everywhere"): the Copilot-style footprint. Nothing is written into any repository.
 *   ~/.cursor/hooks.json          CCO entries merged in (absolute commands carrying --scope user --state-root)
 *   ~/.cursor/agents/<model>-<tier>.md     the five tier subagents (Cursor honors `model:` at user level)
 *   <globalStorage>/cco/          private state root: runtime.json, pricing.json, plugin/ (rule + commands +
 *                                 skills handed to Cursor per workspace via workspaceOpen.pluginPaths),
 *                                 workspaces/<slug>/ (per-project state, pause flag), bin/ (optional binary)
 * Everything is done by the bundled plugin's cco-init (--scope user); this module drives it and keeps a manifest.
 */
import * as crypto from "crypto";
import * as fs from "fs";
import * as os from "os";
import * as path from "path";
import { binaryFileName, findNode, readAgentNames, runPluginScriptAsync, type HookMode, type Options, type RunResult, sameFile } from "./install";

export interface UserPaths {
  root: string;
  manifestPath: string;
  pluginDir: string;
  binDir: string;
  binaryPath: string;
  hooksPath: string;
  agentsDir: string;
}
export interface UserManifest {
  version: number;
  extensionVersion?: string;
  installedAt: string;
  hookMode: HookMode;
  pluginRoot: string;
  binary: string | null;
}
export interface UserStatus {
  installed: boolean;
  hookMode: HookMode | null;
  manifest: UserManifest | null;
  agents: Record<string, string | null>;
}

const CCO_AGENT_NAMES = ["fast-tier", "balanced-tier", "deep-tier", "tier-verifier", "fast-research"];
const GENERATED_PREFIX = "<!-- generated by cursor-ai-cost-optimizer";

export function userPaths(stateRoot: string): UserPaths {
  const cursor = path.join(os.homedir(), ".cursor");
  return {
    root: stateRoot,
    manifestPath: path.join(stateRoot, "extension-manifest.json"),
    pluginDir: path.join(stateRoot, "plugin"),
    binDir: path.join(stateRoot, "bin"),
    binaryPath: path.join(stateRoot, "bin", binaryFileName()),
    hooksPath: path.join(cursor, "hooks.json"),
    agentsDir: path.join(cursor, "agents"),
  };
}

/** Mirrors the plugin's workspaceSlug(): basename + sha1 prefix of the absolute path. */
export function workspaceSlug(workspace: string): string {
  const hash = crypto.createHash("sha1").update(String(workspace)).digest("hex").slice(0, 10);
  return `${path.basename(workspace).replace(/[^A-Za-z0-9._-]+/g, "-").slice(0, 40) || "ws"}-${hash}`;
}
export function workspaceStateDir(stateRoot: string, workspace: string): string {
  return path.join(stateRoot, "workspaces", workspaceSlug(workspace));
}

function readJson<T>(file: string, fallback: T): T {
  try {
    return JSON.parse(fs.readFileSync(file, "utf8")) as T;
  } catch {
    return fallback;
  }
}
function scopeEnv(stateRoot: string): Record<string, string> {
  return { CCO_SCOPE: "user", CCO_STATE_ROOT: stateRoot };
}
function initArgs(stateRoot: string, workspace: string, extra: string[] = []): string[] {
  return ["--workspace", workspace, "--scope", "user", "--state-root", stateRoot, ...extra];
}

export function readUserAgents(stateRoot: string): Record<string, string | null> {
  const p = userPaths(stateRoot);
  const out: Record<string, string | null> = {};
  const names = readAgentNames(path.join(p.root, "agent-names.json"));
  for (const name of CCO_AGENT_NAMES) {
    try {
      const text = fs.readFileSync(path.join(p.agentsDir, `${names[name]}.md`), "utf8");
      out[name] = /^model:\s*(.+)$/m.exec(text)?.[1]?.trim() ?? null;
    } catch {
      out[name] = null;
    }
  }
  return out;
}

export function userStatus(stateRoot: string): UserStatus {
  const p = userPaths(stateRoot);
  const manifest = readJson<UserManifest | null>(p.manifestPath, null);
  const hooks = readJson<{ hooks?: Record<string, Array<{ command?: string }>> } | null>(p.hooksPath, null);
  const hooked = Boolean(hooks && Object.values(hooks.hooks || {}).some((list) => (list || []).some((e) => String(e.command || "").includes("cco-hook") && String(e.command || "").includes("--scope user"))));
  const agents = readUserAgents(stateRoot);
  const installed = Boolean(manifest) && hooked && fs.existsSync(path.join(p.agentsDir, `${readAgentNames(path.join(p.root, "agent-names.json"))["fast-tier"]}.md`));
  return { installed, hookMode: manifest?.hookMode ?? null, manifest, agents };
}

/** Paused for a project = the per-workspace cco.json under the state root says enabled:false. */
export function workspacePaused(stateRoot: string, workspace: string): boolean {
  const cfg = readJson<{ enabled?: boolean } | null>(path.join(workspaceStateDir(stateRoot, workspace), "cco.json"), null);
  return Boolean(cfg && cfg.enabled === false);
}

export function decideUserHookMode(opts: Options): HookMode {
  const pref = opts.hookRuntime || "auto";
  const hasBinary = Boolean(opts.binaryPath && fs.existsSync(opts.binaryPath));
  if (pref === "binary") {
    if (!hasBinary) {
      throw new Error("costOptimizer.hookRuntime is \"binary\" but this extension build has no hook binary for this platform.");
    }
    return "binary";
  }
  if (pref === "node") {
    return "node";
  }
  // Everywhere is machine-local by nature (hooks.json already points into this extension's folder), so the
  // compiled binary is preferred: ~37 ms per tool call instead of ~140 ms for a Node start.
  return hasBinary ? "binary" : findNode(opts.nodePath) ? "node" : "node";
}

export interface UserInstallResult {
  hookMode: HookMode;
  init: RunResult;
  agents: Record<string, string | null>;
  paths: UserPaths;
}

/** Idempotent: cco-init merges hook entries, rewrites the agents and the runtime plugin, keeps other state. */
export async function installUser(opts: Options, stateRoot: string, workspace: string = os.homedir(), signal?: AbortSignal): Promise<UserInstallResult> {
  const p = userPaths(stateRoot);
  fs.mkdirSync(p.root, { recursive: true });
  const hookMode = decideUserHookMode(opts);
  // The compiled hook finds the full plugin (config defaults, agent templates, rule) through this pointer,
  // next to its bin/ folder; the doctor rewrites it whenever the extension folder moves (updates).
  fs.writeFileSync(path.join(p.root, "plugin-path.txt"), `${opts.pluginRoot}\n`, "utf8");
  let hookCommand: string | null = null;
  if (hookMode === "binary") {
    fs.mkdirSync(p.binDir, { recursive: true });
    fs.copyFileSync(opts.binaryPath as string, p.binaryPath);
    if (process.platform !== "win32") {
      fs.chmodSync(p.binaryPath, 0o755);
    }
    hookCommand = p.binaryPath;
  } else {
    fs.rmSync(p.binDir, { recursive: true, force: true });
  }
  const init = await runPluginScriptAsync(workspace, "cco-init.mjs", initArgs(stateRoot, workspace, [opts.probe ? "--probe" : "--no-probe", ...(hookCommand ? ["--hook-command", hookCommand] : [])]), opts, scopeEnv(stateRoot), signal);
  if (!init.ran) {
    throw new Error(init.error || "setup could not run");
  }
  if (init.status !== 0) {
    throw new Error(`cco-init failed (${init.runtime}): ${init.error}\n${init.stdout}`);
  }
  const manifest: UserManifest = { version: 1, extensionVersion: opts.extensionVersion, installedAt: new Date().toISOString(), hookMode, pluginRoot: opts.pluginRoot, binary: hookCommand };
  fs.writeFileSync(p.manifestPath, `${JSON.stringify(manifest, null, 2)}\n`, "utf8");
  return { hookMode, init, agents: readUserAgents(stateRoot), paths: p };
}

/** After an extension update the bundled plugin path (and binary) move: re-run the idempotent install once. */
export async function doctorUser(opts: Options, stateRoot: string): Promise<{ installed: boolean; changed: boolean; actions: string[] }> {
  const s = userStatus(stateRoot);
  if (!s.manifest) {
    return { installed: false, changed: false, actions: [] };
  }
  const p = userPaths(stateRoot);
  const actions: string[] = [];
  if (s.manifest.pluginRoot !== opts.pluginRoot || (opts.extensionVersion && s.manifest.extensionVersion !== opts.extensionVersion) || !s.installed) {
    actions.push("repointed_after_update");
  }
  // Same version reinstalled with a different bundled binary (a rebuilt VSIX): the copy under the state root is what runs.
  if (s.manifest.hookMode === "binary" && opts.binaryPath && fs.existsSync(opts.binaryPath) && !sameFile(opts.binaryPath, p.binaryPath)) {
    actions.push("binary_refreshed");
  }
  // Pre-0.3 tier subagents (cco-fast, cco-deep, …) still present: the model-named ones replace them.
  if (fs.existsSync(p.agentsDir) && fs.readdirSync(p.agentsDir).some((f) => /^cco-(fast|balanced|deep|explore|verifier)\.md$/.test(f))) {
    actions.push("legacy_agents_replaced");
  }
  if (!actions.length) {
    return { installed: true, changed: false, actions: [] };
  }
  await installUser({ ...opts, probe: false }, stateRoot);
  return { installed: true, changed: true, actions };
}

export function pauseWorkspace(opts: Options, stateRoot: string, workspace: string, paused: boolean): Promise<RunResult> {
  return runPluginScriptAsync(workspace, "cco-init.mjs", initArgs(stateRoot, workspace, [paused ? "--disable" : "--enable"]), opts, scopeEnv(stateRoot));
}

/** Removes the hook entries, the generated agents and the whole private state root. Nothing is left behind. */
export async function uninstallUser(opts: Options, stateRoot: string): Promise<{ init: RunResult; removed: string[] }> {
  const p = userPaths(stateRoot);
  const init = await runPluginScriptAsync(os.homedir(), "cco-init.mjs", initArgs(stateRoot, os.homedir(), ["--uninstall"]), opts, scopeEnv(stateRoot));
  // in-process fallback (same effect) if the plugin script could not run
  if (!init.ran || init.status !== 0) {
    const hooks = readJson<{ hooks?: Record<string, Array<{ command?: string }>> } | null>(p.hooksPath, null);
    if (hooks) {
      const kept: Record<string, Array<{ command?: string }>> = {};
      for (const [event, list] of Object.entries(hooks.hooks || {})) {
        const rest = (list || []).filter((e) => !String(e.command || "").includes("cco-hook"));
        if (rest.length) {
          kept[event] = rest;
        }
      }
      if (Object.keys(kept).length) {
        fs.writeFileSync(p.hooksPath, `${JSON.stringify({ ...hooks, hooks: kept }, null, 2)}\n`, "utf8");
      } else {
        fs.rmSync(p.hooksPath, { force: true });
      }
    }
    for (const name of CCO_AGENT_NAMES) {
      const file = path.join(p.agentsDir, `${name}.md`);
      try {
        if (fs.readFileSync(file, "utf8").includes(GENERATED_PREFIX)) {
          fs.rmSync(file, { force: true });
        }
      } catch {}
    }
    fs.rmSync(p.root, { recursive: true, force: true });
  }
  return { init, removed: [p.hooksPath, `${p.agentsDir}/<model>-<tier>.md`, p.root] };
}

/** Kill switch: strip CCO's entries from ~/.cursor/hooks.json only (agents, state and manifest stay; Set Up / Update restores). */
export function stripUserHooks(stateRoot: string): boolean {
  const p = userPaths(stateRoot);
  const hooks = readJson<{ hooks?: Record<string, Array<{ command?: string }>> } | null>(p.hooksPath, null);
  if (!hooks) {
    return false;
  }
  const kept: Record<string, Array<{ command?: string }>> = {};
  let dropped = 0;
  for (const [event, list] of Object.entries(hooks.hooks || {})) {
    const rest = (list || []).filter((e) => !String(e.command || "").includes("cco-hook"));
    dropped += (list || []).length - rest.length;
    if (rest.length) {
      kept[event] = rest;
    }
  }
  if (!dropped) {
    return false;
  }
  if (Object.keys(kept).length) {
    fs.writeFileSync(p.hooksPath, `${JSON.stringify({ ...hooks, hooks: kept }, null, 2)}\n`, "utf8");
  } else {
    fs.rmSync(p.hooksPath, { force: true });
  }
  return true;
}

/** The exact preToolUse command Cursor would run (first CCO entry), or null. */
export function userHookCommand(stateRoot: string): string | null {
  const p = userPaths(stateRoot);
  const hooks = readJson<{ hooks?: Record<string, Array<{ command?: string }>> } | null>(p.hooksPath, null);
  const entry = (hooks?.hooks?.preToolUse || []).find((e) => String(e.command || "").includes("cco-hook"));
  return entry?.command ?? null;
}

// ---------------------------------------------------------------------------------------------
// copies of the Cursor plugin next to the extension
// ---------------------------------------------------------------------------------------------

export interface PluginCopy {
  path: string;
  kind: "local" | "marketplace";
  version: string | null;
}

function isOurPluginDir(dir: string): { yes: boolean; version: string | null } {
  try {
    const manifest = JSON.parse(fs.readFileSync(path.join(dir, ".cursor-plugin", "plugin.json"), "utf8")) as { name?: string; version?: string };
    if (String(manifest.name || "").toLowerCase() === "cursor-ai-cost-optimizer") {
      return { yes: true, version: manifest.version ? String(manifest.version) : null };
    }
  } catch {}
  // an unpacked copy without a manifest: our tier subagents and our hook dispatcher
  if (fs.existsSync(path.join(dir, "agents", "cco-fast.md")) && fs.existsSync(path.join(dir, "hooks", "hooks.json"))) {
    return { yes: true, version: null };
  }
  return { yes: false, version: null };
}

/**
 * The same product installed as a Cursor plugin (a `~/.cursor/plugins/local` copy from the CLI, or the marketplace
 * cache) next to this extension: its `cco-*` subagents run on the chat model (plugin agents cannot set a model), its
 * hooks run a second time, and Cursor's subagent list then keeps those names and rejects ours.
 */
export function findPluginCopies(home: string = os.homedir()): PluginCopy[] {
  const out: PluginCopy[] = [];
  const root = path.join(home, ".cursor", "plugins");
  const visit = (dir: string, kind: PluginCopy["kind"], depth: number) => {
    let entries: fs.Dirent[] = [];
    try {
      entries = fs.readdirSync(dir, { withFileTypes: true });
    } catch {
      return;
    }
    for (const e of entries) {
      if (!e.isDirectory()) {
        continue;
      }
      const candidate = path.join(dir, e.name);
      const probe = isOurPluginDir(candidate);
      if (probe.yes) {
        out.push({ path: candidate, kind, version: probe.version });
      } else if (depth > 0) {
        visit(candidate, kind, depth - 1);
      }
    }
  };
  visit(path.join(root, "local"), "local", 1);
  visit(path.join(root, "cache"), "marketplace", 2);
  return out;
}

/** Local copies are moved under the state root (reversible); marketplace copies are reported for the user to uninstall. */
export function retirePluginCopies(stateRoot: string, copies: PluginCopy[]): { retired: string[]; marketplace: string[] } {
  const retired: string[] = [];
  const marketplace: string[] = [];
  for (const c of copies) {
    if (c.kind !== "local") {
      marketplace.push(c.path);
      continue;
    }
    const dest = path.join(stateRoot, "retired-plugins", `${path.basename(c.path)}-${new Date().toISOString().replace(/[:.]/g, "-")}`);
    try {
      fs.mkdirSync(path.dirname(dest), { recursive: true });
      try {
        fs.renameSync(c.path, dest);
      } catch {
        fs.cpSync(c.path, dest, { recursive: true });
        fs.rmSync(c.path, { recursive: true, force: true });
      }
      retired.push(c.path);
    } catch {
      marketplace.push(c.path);
    }
  }
  return { retired, marketplace };
}

/**
 * A remote window (WSL, SSH, container) lists subagents when it opens and does not refresh the list, so subagent
 * files written after that moment are unknown to it until a reload. When the extension writes them in such a
 * window it records what the window can still use: the generated names that existed before (aliases now, on the
 * new models), or none at all for a first setup; the hooks then route under those names, or keep the work in the
 * chat, instead of sending the model a name the Task tool will reject. workspaceOpen rewrites the record when a
 * window opens with the files in place.
 */
export function recordAgentsWrittenAfterOpen(stateRoot: string, namesBefore: string[], windowStartedAt: number, remote: boolean): { written: boolean; noneOfOurs: boolean } {
  const file = path.join(stateRoot, "window-agents.json");
  if (!remote) {
    // a local window picks up new subagent files itself: the names written now are the ones to hand out
    try {
      fs.rmSync(file, { force: true });
    } catch {}
    return { written: false, noneOfOurs: false };
  }
  try {
    const existing = JSON.parse(fs.readFileSync(file, "utf8")) as { ts?: string; source?: string };
    if (existing?.ts && Date.parse(existing.ts) >= windowStartedAt && existing.source === "workspaceOpen") {
      return { written: false, noneOfOurs: false }; // this window recorded its own list: the files were there when it opened
    }
  } catch {}
  const names = [...new Set(namesBefore)].sort();
  const noneOfOurs = !names.some((n) => /^cco-(fast|balanced|deep|explore|verifier)$|-(fast|balanced|deep|research|verifier)$|-tier$|^fast-research$|^tier-verifier$/.test(n));
  fs.mkdirSync(stateRoot, { recursive: true });
  fs.writeFileSync(file, `${JSON.stringify({ ts: new Date().toISOString(), source: "written_after_open", names, noneOfOurs }, null, 2)}\n`, "utf8");
  return { written: true, noneOfOurs };
}

/** Generated subagent files present now (any name), for recordAgentsWrittenAfterOpen. */
export function generatedAgentNames(): string[] {
  const dir = path.join(os.homedir(), ".cursor", "agents");
  const out: string[] = [];
  try {
    for (const f of fs.readdirSync(dir)) {
      if (!f.endsWith(".md")) continue;
      try {
        if (fs.readFileSync(path.join(dir, f), "utf8").includes(GENERATED_PREFIX)) out.push(f.slice(0, -3));
      } catch {}
    }
  } catch {}
  return out.sort();
}
