/**
 * User scope ("Everywhere"): the Copilot-style footprint. Nothing is written into any repository.
 *   ~/.cursor/hooks.json          CCO entries merged in (absolute commands carrying --scope user --state-root)
 *   ~/.cursor/agents/*-tier.md     the five tier subagents (Cursor honors `model:` at user level)
 *   <globalStorage>/cco/          private state root: runtime.json, pricing.json, plugin/ (rule + commands +
 *                                 skills handed to Cursor per workspace via workspaceOpen.pluginPaths),
 *                                 workspaces/<slug>/ (per-project state, pause flag), bin/ (optional binary)
 * Everything is done by the bundled plugin's cco-init (--scope user); this module drives it and keeps a manifest.
 */
import * as crypto from "crypto";
import * as fs from "fs";
import * as os from "os";
import * as path from "path";
import { binaryFileName, findNode, readAgentNames, runPluginScriptAsync, type HookMode, type Options, type RunResult } from "./install";

export interface UserPaths {
  root: string;
  manifestPath: string;
  pluginDir: string;
  binDir: string;
  binaryPath: string;
  hooksPath: string;
  agentsDir: string;
}
export interface UserManifest {
  version: number;
  extensionVersion?: string;
  installedAt: string;
  hookMode: HookMode;
  pluginRoot: string;
  binary: string | null;
}
export interface UserStatus {
  installed: boolean;
  hookMode: HookMode | null;
  manifest: UserManifest | null;
  agents: Record<string, string | null>;
}

const CCO_AGENT_NAMES = ["fast-tier", "balanced-tier", "deep-tier", "tier-verifier", "fast-research"];
const GENERATED_PREFIX = "<!-- generated by cursor-ai-cost-optimizer";

export function userPaths(stateRoot: string): UserPaths {
  const cursor = path.join(os.homedir(), ".cursor");
  return {
    root: stateRoot,
    manifestPath: path.join(stateRoot, "extension-manifest.json"),
    pluginDir: path.join(stateRoot, "plugin"),
    binDir: path.join(stateRoot, "bin"),
    binaryPath: path.join(stateRoot, "bin", binaryFileName()),
    hooksPath: path.join(cursor, "hooks.json"),
    agentsDir: path.join(cursor, "agents"),
  };
}

/** Mirrors the plugin's workspaceSlug(): basename + sha1 prefix of the absolute path. */
export function workspaceSlug(workspace: string): string {
  const hash = crypto.createHash("sha1").update(String(workspace)).digest("hex").slice(0, 10);
  return `${path.basename(workspace).replace(/[^A-Za-z0-9._-]+/g, "-").slice(0, 40) || "ws"}-${hash}`;
}
export function workspaceStateDir(stateRoot: string, workspace: string): string {
  return path.join(stateRoot, "workspaces", workspaceSlug(workspace));
}

function readJson<T>(file: string, fallback: T): T {
  try {
    return JSON.parse(fs.readFileSync(file, "utf8")) as T;
  } catch {
    return fallback;
  }
}
function scopeEnv(stateRoot: string): Record<string, string> {
  return { CCO_SCOPE: "user", CCO_STATE_ROOT: stateRoot };
}
function initArgs(stateRoot: string, workspace: string, extra: string[] = []): string[] {
  return ["--workspace", workspace, "--scope", "user", "--state-root", stateRoot, ...extra];
}

export function readUserAgents(stateRoot: string): Record<string, string | null> {
  const p = userPaths(stateRoot);
  const out: Record<string, string | null> = {};
  const names = readAgentNames(path.join(p.root, "agent-names.json"));
  for (const name of CCO_AGENT_NAMES) {
    try {
      const text = fs.readFileSync(path.join(p.agentsDir, `${names[name]}.md`), "utf8");
      out[name] = /^model:\s*(.+)$/m.exec(text)?.[1]?.trim() ?? null;
    } catch {
      out[name] = null;
    }
  }
  return out;
}

export function userStatus(stateRoot: string): UserStatus {
  const p = userPaths(stateRoot);
  const manifest = readJson<UserManifest | null>(p.manifestPath, null);
  const hooks = readJson<{ hooks?: Record<string, Array<{ command?: string }>> } | null>(p.hooksPath, null);
  const hooked = Boolean(hooks && Object.values(hooks.hooks || {}).some((list) => (list || []).some((e) => String(e.command || "").includes("cco-hook") && String(e.command || "").includes("--scope user"))));
  const agents = readUserAgents(stateRoot);
  const installed = Boolean(manifest) && hooked && fs.existsSync(path.join(p.agentsDir, `${readAgentNames(path.join(p.root, "agent-names.json"))["fast-tier"]}.md`));
  return { installed, hookMode: manifest?.hookMode ?? null, manifest, agents };
}

/** Paused for a project = the per-workspace cco.json under the state root says enabled:false. */
export function workspacePaused(stateRoot: string, workspace: string): boolean {
  const cfg = readJson<{ enabled?: boolean } | null>(path.join(workspaceStateDir(stateRoot, workspace), "cco.json"), null);
  return Boolean(cfg && cfg.enabled === false);
}

export function decideUserHookMode(opts: Options): HookMode {
  const pref = opts.hookRuntime || "auto";
  const hasBinary = Boolean(opts.binaryPath && fs.existsSync(opts.binaryPath));
  if (pref === "binary") {
    if (!hasBinary) {
      throw new Error("cco.hookRuntime is \"binary\" but this extension build has no hook binary for this platform.");
    }
    return "binary";
  }
  if (pref === "node") {
    return "node";
  }
  // Everywhere is machine-local by nature (hooks.json already points into this extension's folder), so the
  // compiled binary is preferred: ~37 ms per tool call instead of ~140 ms for a Node start.
  return hasBinary ? "binary" : findNode(opts.nodePath) ? "node" : "node";
}

export interface UserInstallResult {
  hookMode: HookMode;
  init: RunResult;
  agents: Record<string, string | null>;
  paths: UserPaths;
}

/** Idempotent: cco-init merges hook entries, rewrites the agents and the runtime plugin, keeps other state. */
export async function installUser(opts: Options, stateRoot: string, workspace: string = os.homedir(), signal?: AbortSignal): Promise<UserInstallResult> {
  const p = userPaths(stateRoot);
  fs.mkdirSync(p.root, { recursive: true });
  const hookMode = decideUserHookMode(opts);
  // The compiled hook finds the full plugin (config defaults, agent templates, rule) through this pointer,
  // next to its bin/ folder; the doctor rewrites it whenever the extension folder moves (updates).
  fs.writeFileSync(path.join(p.root, "plugin-path.txt"), `${opts.pluginRoot}\n`, "utf8");
  let hookCommand: string | null = null;
  if (hookMode === "binary") {
    fs.mkdirSync(p.binDir, { recursive: true });
    fs.copyFileSync(opts.binaryPath as string, p.binaryPath);
    if (process.platform !== "win32") {
      fs.chmodSync(p.binaryPath, 0o755);
    }
    hookCommand = p.binaryPath;
  } else {
    fs.rmSync(p.binDir, { recursive: true, force: true });
  }
  const init = await runPluginScriptAsync(workspace, "cco-init.mjs", initArgs(stateRoot, workspace, [opts.probe ? "--probe" : "--no-probe", ...(hookCommand ? ["--hook-command", hookCommand] : [])]), opts, scopeEnv(stateRoot), signal);
  if (!init.ran) {
    throw new Error(init.error || "setup could not run");
  }
  if (init.status !== 0) {
    throw new Error(`cco-init failed (${init.runtime}): ${init.error}\n${init.stdout}`);
  }
  const manifest: UserManifest = { version: 1, extensionVersion: opts.extensionVersion, installedAt: new Date().toISOString(), hookMode, pluginRoot: opts.pluginRoot, binary: hookCommand };
  fs.writeFileSync(p.manifestPath, `${JSON.stringify(manifest, null, 2)}\n`, "utf8");
  return { hookMode, init, agents: readUserAgents(stateRoot), paths: p };
}

/** After an extension update the bundled plugin path (and binary) move: re-run the idempotent install once. */
export async function doctorUser(opts: Options, stateRoot: string): Promise<{ installed: boolean; changed: boolean; actions: string[] }> {
  const s = userStatus(stateRoot);
  if (!s.manifest) {
    return { installed: false, changed: false, actions: [] };
  }
  const stale = s.manifest.pluginRoot !== opts.pluginRoot || (opts.extensionVersion && s.manifest.extensionVersion !== opts.extensionVersion) || !s.installed;
  if (!stale) {
    return { installed: true, changed: false, actions: [] };
  }
  await installUser({ ...opts, probe: false }, stateRoot);
  return { installed: true, changed: true, actions: ["repointed_after_update"] };
}

export function pauseWorkspace(opts: Options, stateRoot: string, workspace: string, paused: boolean): Promise<RunResult> {
  return runPluginScriptAsync(workspace, "cco-init.mjs", initArgs(stateRoot, workspace, [paused ? "--disable" : "--enable"]), opts, scopeEnv(stateRoot));
}

/** Removes the hook entries, the generated agents and the whole private state root. Nothing is left behind. */
export async function uninstallUser(opts: Options, stateRoot: string): Promise<{ init: RunResult; removed: string[] }> {
  const p = userPaths(stateRoot);
  const init = await runPluginScriptAsync(os.homedir(), "cco-init.mjs", initArgs(stateRoot, os.homedir(), ["--uninstall"]), opts, scopeEnv(stateRoot));
  // in-process fallback (same effect) if the plugin script could not run
  if (!init.ran || init.status !== 0) {
    const hooks = readJson<{ hooks?: Record<string, Array<{ command?: string }>> } | null>(p.hooksPath, null);
    if (hooks) {
      const kept: Record<string, Array<{ command?: string }>> = {};
      for (const [event, list] of Object.entries(hooks.hooks || {})) {
        const rest = (list || []).filter((e) => !String(e.command || "").includes("cco-hook"));
        if (rest.length) {
          kept[event] = rest;
        }
      }
      if (Object.keys(kept).length) {
        fs.writeFileSync(p.hooksPath, `${JSON.stringify({ ...hooks, hooks: kept }, null, 2)}\n`, "utf8");
      } else {
        fs.rmSync(p.hooksPath, { force: true });
      }
    }
    for (const name of CCO_AGENT_NAMES) {
      const file = path.join(p.agentsDir, `${name}.md`);
      try {
        if (fs.readFileSync(file, "utf8").includes(GENERATED_PREFIX)) {
          fs.rmSync(file, { force: true });
        }
      } catch {}
    }
    fs.rmSync(p.root, { recursive: true, force: true });
  }
  return { init, removed: [p.hooksPath, `${p.agentsDir}/*-tier.md`, p.root] };
}

/** Kill switch: strip CCO's entries from ~/.cursor/hooks.json only (agents, state and manifest stay; Set Up / Update restores). */
export function stripUserHooks(stateRoot: string): boolean {
  const p = userPaths(stateRoot);
  const hooks = readJson<{ hooks?: Record<string, Array<{ command?: string }>> } | null>(p.hooksPath, null);
  if (!hooks) {
    return false;
  }
  const kept: Record<string, Array<{ command?: string }>> = {};
  let dropped = 0;
  for (const [event, list] of Object.entries(hooks.hooks || {})) {
    const rest = (list || []).filter((e) => !String(e.command || "").includes("cco-hook"));
    dropped += (list || []).length - rest.length;
    if (rest.length) {
      kept[event] = rest;
    }
  }
  if (!dropped) {
    return false;
  }
  if (Object.keys(kept).length) {
    fs.writeFileSync(p.hooksPath, `${JSON.stringify({ ...hooks, hooks: kept }, null, 2)}\n`, "utf8");
  } else {
    fs.rmSync(p.hooksPath, { force: true });
  }
  return true;
}

/** The exact preToolUse command Cursor would run (first CCO entry), or null. */
export function userHookCommand(stateRoot: string): string | null {
  const p = userPaths(stateRoot);
  const hooks = readJson<{ hooks?: Record<string, Array<{ command?: string }>> } | null>(p.hooksPath, null);
  const entry = (hooks?.hooks?.preToolUse || []).find((e) => String(e.command || "").includes("cco-hook"));
  return entry?.command ?? null;
}
