#!/usr/bin/env node
// bundle copy generated by scripts/sync-assets.mjs: main-guard keyed on CCO_HOOK_MAIN (see resources/entry/cco-hook-bundle.mjs)
/**
 * Single hook entry point: `cco-hook <event>` reads the hook payload on stdin and dispatches.
 * Used by hooks.json (`node ./scripts/cco-hook.mjs sessionStart`) and by the compiled
 * per-platform binaries shipped with the VS Code extension (`cco-hook-<platform> sessionStart`).
 * Unknown events are fail-open.
 */
import { isMain, applyScopeArgs, workspacePaths } from "./lib/common.mjs";
applyScopeArgs();
import { pathToFileURL } from "node:url";
import path from "node:path";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const event = String(process.argv[2] || "").trim();

const SCRIPTS = {
  sessionStart: "cco-session-start.mjs",
  workspaceOpen: "cco-workspace-open.mjs",
  beforeSubmitPrompt: "cco-prompt-capture.mjs",
  preToolUse: null, // decided below by tool name
  postToolUse: "cco-task-result.mjs",
  subagentStop: "cco-task-result.mjs",
  beforeShellExecution: "cco-shell-guard.mjs",
  sessionEnd: "cco-session-end.mjs"
};

async function readStdin() {
  return new Promise((resolve) => {
    let raw = "";
    if (process.stdin.isTTY) {
      resolve("");
      return;
    }
    process.stdin.setEncoding("utf8");
    process.stdin.on("data", (c) => {
      raw += c;
    });
    process.stdin.on("end", () => resolve(raw));
    process.stdin.on("error", () => resolve(raw));
  });
}

import fs from "node:fs";
import os from "node:os";
import crypto from "node:crypto";

/**
 * The same hook can be invoked twice for one event (plugin-declared hooks in the CLI plus
 * user-level hooks.json, or Cursor retrying). Replay the first result instead of acting twice.
 */
function dedupeKeyFor(eventName, raw) {
  let p = {};
  try {
    p = JSON.parse(raw || "{}");
  } catch {}
  const parts = [eventName, p.conversation_id || "", p.generation_id || "", p.tool_use_id || "", p.tool_name || "", JSON.stringify(p.tool_input || p.command || p.prompt || "")];
  return { key: crypto.createHash("sha1").update(parts.join("|")).digest("hex"), workspace: Array.isArray(p.workspace_roots) ? p.workspace_roots[0] : null, hasId: Boolean(p.conversation_id || p.generation_id) };
}

function dedupeDir(workspace) {
  return workspace ? workspacePaths(workspace).dedupeDir : path.join(os.tmpdir(), "cco-dedupe");
}

function sleepMs(ms) {
  const end = Date.now() + ms;
  while (Date.now() < end) {
    Atomics.wait(new Int32Array(new SharedArrayBuffer(4)), 0, 0, Math.min(25, end - Date.now()));
  }
}

/**
 * Claim the right to handle this event. Returns { owner: true } when this process should run the
 * hook, or { owner: false, replay } when another invocation already handled (or is handling) it.
 */
function claim(dir, key) {
  const lock = path.join(dir, `${key}.lock`);
  const result = path.join(dir, `${key}.json`);
  try {
    fs.mkdirSync(dir, { recursive: true });
    const fd = fs.openSync(lock, "wx");
    fs.closeSync(fd);
    return { owner: true, result, lock };
  } catch (error) {
    if (error?.code !== "EEXIST") {
      return { owner: true, result, lock: null };
    }
  }
  // Someone else owns it: wait briefly for their result and replay it.
  const deadline = Date.now() + 8_000;
  while (Date.now() < deadline) {
    try {
      const stat = fs.statSync(result);
      if (Date.now() - stat.mtimeMs < 60_000) {
        return { owner: false, replay: fs.readFileSync(result, "utf8") };
      }
    } catch {}
    try {
      if (Date.now() - fs.statSync(lock).mtimeMs > 60_000) {
        // Stale lock from a crashed run: take over.
        fs.unlinkSync(lock);
        return claim(dir, key);
      }
    } catch {}
    sleepMs(50);
  }
  return { owner: false, replay: null };
}

function writeReplay(result, output) {
  try {
    fs.writeFileSync(result, output, "utf8");
    const dir = path.dirname(result);
    for (const name of fs.readdirSync(dir)) {
      const file = path.join(dir, name);
      try {
        if (Date.now() - fs.statSync(file).mtimeMs > 120_000) {
          fs.unlinkSync(file);
        }
      } catch {}
    }
  } catch {}
}

export async function dispatch(event, raw) {
  return dispatchWith(event, raw);
}

async function dispatchWith(eventName, raw) {
  const { key, workspace, hasId } = dedupeKeyFor(eventName, raw);
  const dir = dedupeDir(workspace);
  let claimed = { owner: true, result: null };
  if (hasId && eventName !== "sessionEnd") {
    claimed = claim(dir, key);
    if (!claimed.owner) {
      const replay = claimed.replay || `${JSON.stringify({ continue: true, permission: "allow" })}\n`;
      return replay.endsWith("\n") ? replay : `${replay}\n`;
    }
  }
  let script = SCRIPTS[eventName];
  if (eventName === "preToolUse") {
    let toolName = "";
    try {
      toolName = String(JSON.parse(raw || "{}").tool_name || "");
    } catch {}
    script = toolName === "Task" ? "cco-task-guard.mjs" : "cco-tool-gate.mjs";
  }
  if (!script) {
    const out = `${JSON.stringify(eventName === "beforeShellExecution" ? { continue: true, permission: "allow" } : { continue: true })}\n`;
    if (claimed.result) {
      writeReplay(claimed.result, out);
    }
    return out;
  }
  // Re-feed stdin to the target script by spawning it with the same payload.
  const { spawnSync } = await import("node:child_process");
  const res = spawnSync(process.execPath, [path.join(here, script), eventName], { input: raw, encoding: "utf8", timeout: 40_000 });
  const output = res.stdout ? res.stdout : `${JSON.stringify({ continue: true, permission: "allow" })}\n`;
  if (claimed.result) {
    writeReplay(claimed.result, output);
  }
  return output;
}

async function main() {
  const raw = await readStdin();
  process.stdout.write(await dispatchWith(event, raw));
}

if (process.env.CCO_HOOK_MAIN === "cco-hook.mjs" || process.env.CCO_HOOK_MAIN === "cco-hook.mjs") {
  main().catch(() => {
    process.stdout.write(`${JSON.stringify({ continue: true, permission: "allow" })}\n`);
  });
}

export { SCRIPTS, pathToFileURL };
