#!/usr/bin/env node
// bundle copy generated by scripts/sync-assets.mjs: main-guard keyed on CCO_HOOK_MAIN (see resources/entry/cco-hook-bundle.mjs)
/**
 * Summarize routing decisions, gate activity, and learning state for a workspace.
 *   node scripts/cco-report.mjs --workspace <root> [--json]
 */
import path from "node:path";
import { parseArgs, readJsonl, readJsonSafe, workspacePaths, TIERS, isMain, applyScopeArgs } from "./lib/common.mjs";
applyScopeArgs();
import { loadConfig } from "./lib/config.mjs";
import { loadPricing, resolveModelPrice } from "./lib/pricing.mjs";

export function buildReport(workspace) {
  const paths = workspacePaths(workspace);
  const config = loadConfig(workspace);
  const decisions = readJsonl(paths.decisionsPath);
  const hooks = readJsonl(paths.hooksLogPath);
  const runtime = readJsonSafe(paths.runtimePath);
  const state = readJsonSafe(paths.jointStatePath);
  const pricing = loadPricing(paths.pricingPath);

  const byTier = Object.fromEntries(TIERS.map((t) => [t, 0]));
  let rewritten = 0;
  const reasons = {};
  for (const d of decisions) {
    const tier = String(d.final || "").replace(/^cco-/, "").replace(/-tier$/, "");
    if (byTier[tier] !== undefined) {
      byTier[tier] += 1;
    }
    if (d.rewritten) {
      rewritten += 1;
      reasons[d.reason] = (reasons[d.reason] || 0) + 1;
    }
  }
  const gate = hooks.filter((h) => h.event === "preToolUse:gate");
  const gateDenials = gate.filter((g) => g.action === "deny").length;
  const gateReasons = {};
  for (const g of gate.filter((x) => x.action === "deny")) {
    gateReasons[g.reason] = (gateReasons[g.reason] || 0) + 1;
  }
  const sessions = hooks.filter((h) => h.event === "sessionStart").length;
  const prompts = hooks.filter((h) => h.event === "beforeSubmitPrompt");
  const heuristicTiers = Object.fromEntries(TIERS.map((t) => [t, prompts.filter((p) => p.heuristic?.tier === t).length]));

  let estimatedSavingsUsd = 0;
  let routedWithEstimates = 0;
  for (const d of decisions) {
    if (Number.isFinite(d.estimateUsd) && Number.isFinite(d.chatEstimateUsd) && d.final !== "chat") {
      estimatedSavingsUsd += Math.max(0, d.chatEstimateUsd - d.estimateUsd);
      routedWithEstimates += 1;
    }
  }

  const models = {};
  for (const tier of TIERS) {
    const model = runtime?.profiles?.[tier]?.model || "inherit";
    const price = model === "inherit" ? null : resolveModelPrice(model, pricing, { overrides: config?.pricing?.overrides });
    models[tier] = { model, input: price?.input ?? null, output: price?.output ?? null };
  }

  const suggestions = [];
  const total = decisions.length;
  if (total >= 10) {
    const fastShare = byTier.fast / total;
    const deepShare = byTier.deep / total;
    if (fastShare < 0.3) {
      suggestions.push(`Only ${(fastShare * 100).toFixed(0)}% of delegations went FAST. If those tasks were simple, raise thresholds.fastMax (currently ${config.thresholds?.fastMax}) by 0.5.`);
    }
    if (deepShare > 0.5) {
      suggestions.push(`${(deepShare * 100).toFixed(0)}% of delegations went DEEP. If quality is fine at BALANCED, lower weights.risk (currently ${config.weights?.risk}) by 0.05 or raise guardrails.riskNoFast.`);
    }
  }
  for (const tier of TIERS) {
    const obs = state?.tiers?.[tier];
    if (obs && obs.count >= (config.learning?.minObservations || 3) && (obs.emaError + obs.emaRework) > (config.learning?.escalateWhenErrorEmaAbove || 0.45)) {
      suggestions.push(`Tier ${tier} (${models[tier].model}) has a high failure/rework EMA (${(obs.emaError + obs.emaRework).toFixed(2)}); CCO is auto-escalating it. Consider a stronger model for this tier via /cco-models.`);
    }
  }
  if (gateDenials > 0 && total === 0) {
    suggestions.push("The gate denied direct work but no delegation was logged; the parent model may be ignoring the routing rule. Check .cursor/cco/state/hooks.jsonl.");
  }
  if (!total && !gate.length) {
    suggestions.push("No routing activity yet. Run a few tasks in Cursor with the plugin enabled, then re-run this report.");
  }

  return {
    workspace,
    generatedAt: new Date().toISOString(),
    sessions,
    delegations: { total, byTier, rewritten, rewriteReasons: reasons },
    savings: { estimatedUsd: Number(estimatedSavingsUsd.toFixed(2)), routedTasks: routedWithEstimates },
    gate: { checks: gate.length, denials: gateDenials, denialReasons: gateReasons },
    promptsCaptured: { total: prompts.length, heuristicTiers },
    models,
    learning: state?.tiers || {},
    suggestions
  };
}

export function renderReport(r) {
  let md = `# CCO report — ${path.basename(r.workspace)}\n\n`;
  md += `- Estimated savings so far: **$${r.savings.estimatedUsd.toFixed(2)}** across ${r.savings.routedTasks} routed task(s) (tier model vs. your chat model, typical token volumes)\n- Sessions seen: ${r.sessions}\n- Delegations: ${r.delegations.total} (fast ${r.delegations.byTier.fast}, balanced ${r.delegations.byTier.balanced}, deep ${r.delegations.byTier.deep}); rerouted by policy: ${r.delegations.rewritten}\n`;
  md += `- Gate: ${r.gate.checks} checks, ${r.gate.denials} denials${Object.keys(r.gate.denialReasons).length ? ` (${Object.entries(r.gate.denialReasons).map(([k, v]) => `${k}: ${v}`).join(", ")})` : ""}\n`;
  md += `- Prompts captured (IDE): ${r.promptsCaptured.total}\n\n`;
  md += "| Tier | Model | $/M in | $/M out |\n|---|---|---:|---:|\n";
  for (const tier of TIERS) {
    const m = r.models[tier];
    md += `| ${tier} | ${m.model} | ${m.input ?? "?"} | ${m.output ?? "?"} |\n`;
  }
  if (Object.keys(r.learning).length) {
    md += "\n## Learning state\n\n| Tier | n | error EMA | rework EMA |\n|---|---:|---:|---:|\n";
    for (const [tier, obs] of Object.entries(r.learning)) {
      md += `| ${tier} | ${obs.count} | ${Number(obs.emaError || 0).toFixed(2)} | ${Number(obs.emaRework || 0).toFixed(2)} |\n`;
    }
  }
  md += "\n## Suggestions\n\n";
  md += r.suggestions.length ? r.suggestions.map((s) => `- ${s}`).join("\n") : "- Nothing to tune yet.";
  md += "\n";
  return md;
}

function main() {
  const args = parseArgs(process.argv.slice(2), { workspace: process.cwd(), json: false });
  const report = buildReport(path.resolve(String(args.workspace)));
  console.log(args.json ? JSON.stringify(report, null, 2) : renderReport(report));
}

if (process.env.CCO_HOOK_MAIN === "cco-report.mjs") {
  main();
}
