#!/usr/bin/env node
// `vscode:uninstall` hook: runs (plain Node, no vscode API) after the extension is uninstalled and the
// editor restarts. It removes everything the "Everywhere" setup wrote (CCO entries in ~/.cursor/hooks.json, the
// generated ~/.cursor/agents/cco-*.md) and the extension's global storage folder in every known Cursor / VS Code
// user-data location. Project files (.cursor/...) of a "this project only" setup are deliberately left alone — they
// belong to the project and are removed with "AI Cost Optimizer: Remove" (or the plugin's cco-init --uninstall).
"use strict";
const fs = require("fs");
const os = require("os");
const path = require("path");

const EXTENSION_ID = "khalidsaidi.cursor-ai-cost-optimizer";

function userDataRoots() {
  const home = os.homedir();
  const roots = [];
  if (process.platform === "win32") {
    const appData = process.env.APPDATA || path.join(home, "AppData", "Roaming");
    roots.push(path.join(appData, "Cursor", "User"), path.join(appData, "Code", "User"), path.join(appData, "Code - Insiders", "User"));
  } else if (process.platform === "darwin") {
    const support = path.join(home, "Library", "Application Support");
    roots.push(path.join(support, "Cursor", "User"), path.join(support, "Code", "User"), path.join(support, "Code - Insiders", "User"));
  } else {
    const config = process.env.XDG_CONFIG_HOME || path.join(home, ".config");
    roots.push(path.join(config, "Cursor", "User"), path.join(config, "Code", "User"), path.join(config, "Code - Insiders", "User"));
    // remote (SSH/WSL) servers keep user data under the server dir
    roots.push(path.join(home, ".cursor-server", "data", "User"), path.join(home, ".vscode-server", "data", "User"));
  }
  return roots;
}

// "Everywhere" setup lives in Cursor's user config: strip CCO's hook entries and the generated subagents.
function cleanUserLevel() {
  const cursor = path.join(os.homedir(), ".cursor");
  const hooksFile = path.join(cursor, "hooks.json");
  try {
    const data = JSON.parse(fs.readFileSync(hooksFile, "utf8"));
    const hooks = {};
    let dropped = 0;
    for (const [event, list] of Object.entries(data.hooks || {})) {
      const kept = (list || []).filter((e) => !String(e.command || "").includes("cco-hook"));
      dropped += (list || []).length - kept.length;
      if (kept.length) hooks[event] = kept;
    }
    if (dropped) {
      if (Object.keys(hooks).length) fs.writeFileSync(hooksFile, JSON.stringify({ ...data, hooks }, null, 2) + "\n");
      else fs.unlinkSync(hooksFile);
      console.log(`[cco uninstall] removed ${dropped} CCO hook entr${dropped === 1 ? "y" : "ies"} from ${hooksFile}`);
    }
  } catch {}
  // Every generated subagent file, whatever its name (model-named, role-named, pre-0.3 cco-*): marker-based.
  let files = [];
  try {
    files = fs.readdirSync(path.join(cursor, "agents")).filter((f) => f.endsWith(".md")).map((f) => path.join(cursor, "agents", f));
  } catch {}
  for (const file of files) {
    try {
      if (fs.readFileSync(file, "utf8").includes("<!-- generated by cursor-ai-cost-optimizer")) {
        fs.unlinkSync(file);
        console.log(`[cco uninstall] removed ${file}`);
      }
    } catch {}
  }
}
cleanUserLevel();

let removed = 0;
for (const root of userDataRoots()) {
  const dir = path.join(root, "globalStorage", EXTENSION_ID);
  try {
    if (fs.existsSync(dir)) {
      fs.rmSync(dir, { recursive: true, force: true });
      console.log(`[cco uninstall] removed ${dir}`);
      removed += 1;
    }
  } catch (error) {
    console.log(`[cco uninstall] could not remove ${dir}: ${error && error.message ? error.message : error}`);
  }
}
console.log(`[cco uninstall] done (${removed} global storage folder(s) removed). Project-scoped files under a repo's .cursor/ (if you chose "this project only") are left in place; run "AI Cost Optimizer: Remove" before removing the extension to clean them.`);
